[package]
name = "AoC2020"
version = "0.1.0"
authors = ["codedsakura <sakura.coded@gmail.com>"]
edition = "2018"

[[bin]]
name = "a"
path = "A.rs"

[[bin]]
name = "b"
path = "B.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
